version: '3'
volumes:
  db:
services:
  db:
    container_name: taskmanagement
    image: postgres:13
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
      
